apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-engine
  labels:
    app: ml-engine
    component: ai-ml
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ml-engine
  template:
    metadata:
      labels:
        app: ml-engine
        component: ai-ml
    spec:
      containers:
      - name: ml-engine
        image: mcp-security/ml-engine:latest
        ports:
        - containerPort: 8092
        resources:
          requests:
            memory: '512Mi'
            cpu: '200m'
          limits:
            memory: '1Gi'
            cpu: '500m'
        livenessProbe:
          httpGet:
            path: /health
            port: 8092
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8092
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ml-engine
  labels:
    app: ml-engine
spec:
  selector:
    app: ml-engine
  ports:
  - name: http
    port: 8092
    targetPort: 8092
  type: ClusterIP
