apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: web-interface-functional
  namespace: argocd
  labels:
    app: web-interface-functional
    component: frontend
spec:
  project: default
  source:
    repoURL: https://github.com/ggkunka/mcp-security-platform.git
    targetRevision: main
    path: gitops/platform/web-interface-functional
  destination:
    server: https://kubernetes.default.svc
    namespace: mcp-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10
