apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-orca-gui
  namespace: mcp-security
  labels:
    app: fortress-orca-gui
    component: frontend
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress-orca-gui
  template:
    metadata:
      labels:
        app: fortress-orca-gui
        component: frontend
        version: v1.0.0
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: web-interface
        image: ghcr.io/ggkunka/fortress-orca-gui:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: API_BASE_URL
          value: "http://api-gateway.mcp-security.svc.cluster.local:8080"
        - name: WEBSOCKET_URL
          value: "ws://websocket-gateway.mcp-security.svc.cluster.local:8088"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-orca-gui
  namespace: mcp-security
  labels:
    app: fortress-orca-gui
    component: frontend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
    protocol: TCP
    name: http
  selector:
    app: fortress-orca-gui
