apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-devops-integration
  namespace: fortress-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress-devops-integration
  template:
    metadata:
      labels:
        app: fortress-devops-integration
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: devops-integration
        image: python:3.11-slim
        ports:
        - containerPort: 8094
        env:
        - name: JENKINS_URL
          value: "http://jenkins.fortress.local"
        - name: GITLAB_URL
          value: "http://gitlab.fortress.local"
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: devops-code
          mountPath: /app
        command: ["/bin/bash"]
        args:
        - -c
        - |
          cd /app
          pip install fastapi uvicorn requests pydantic
          python main.py
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8094
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8094
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: devops-code
        configMap:
          name: fortress-devops-code
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-devops-integration
  namespace: fortress-system
spec:
  selector:
    app: fortress-devops-integration
  ports:
  - port: 8094
    targetPort: 8094
  type: ClusterIP
