# Fortress API Gateway with Istio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-gateway
  namespace: fortress-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress-gateway
  template:
    metadata:
      labels:
        app: fortress-gateway
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: gateway
        image: nginx:alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - name: gateway-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: gateway-config
        configMap:
          name: fortress-gateway-config

---
apiVersion: v1
kind: Service
metadata:
  name: fortress-gateway
  namespace: fortress-system
spec:
  selector:
    app: fortress-gateway
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
