# Fortress Auth Service with Istio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-auth
  namespace: fortress-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress-auth
  template:
    metadata:
      labels:
        app: fortress-auth
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: auth-service
        image: python:3.11-slim
        ports:
        - containerPort: 8001
        env:
        - name: DATABASE_URL
          value: "postgresql://fortress_user:fortress_secure_password@fortress-postgresql:5432/fortress_security"
        - name: REDIS_URL
          value: "redis://fortress-redis:6379"
        command: ["/bin/sh"]
        args: ["-c", "pip install fastapi uvicorn sqlalchemy psycopg2-binary redis && python -c 'print(\"Auth Ready\")' && sleep 3600"]

---
apiVersion: v1
kind: Service
metadata:
  name: fortress-auth
  namespace: fortress-system
spec:
  selector:
    app: fortress-auth
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
