apiVersion: v1
kind: Namespace
metadata:
  name: mcp-security
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: mcp-security-platform
    app.kubernetes.io/component: namespace
    security.policy/tier: production
  annotations:
    istio.io/rev: default
---
apiVersion: v1
kind: Namespace
metadata:
  name: mcp-security-monitoring
  labels:
    istio-injection: enabled
    app.kubernetes.io/name: mcp-security-platform
    app.kubernetes.io/component: monitoring
  annotations:
    istio.io/rev: default