apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway
  labels:
    app: graphql-gateway
    component: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
        component: api-gateway
    spec:
      containers:
      - name: graphql-gateway
        image: mcp-security/graphql-gateway:latest
        ports:
        - containerPort: 8087
        env:
        - name: SERVICE_NAME
          value: "graphql-gateway"
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_URL
          value: "redis://redis-master:6379/0"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8087
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway
  labels:
    app: graphql-gateway
    component: api-gateway
spec:
  selector:
    app: graphql-gateway
  ports:
  - name: http
    port: 8087
    targetPort: 8087
    protocol: TCP
  type: ClusterIP
