apiVersion: v1
kind: Namespace
metadata:
  name: fortress-system
  labels:
    name: fortress-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: neo4j-config
  namespace: fortress-system
data:
  NEO4J_AUTH: "neo4j/fortress_secure_password"
  NEO4J_dbms_default_database: "fortress"
  NEO4J_dbms_security_procedures_unrestricted: "apoc.*,algo.*"
  NEO4J_dbms_security_procedures_allowlist: "apoc.*,algo.*"
  NEO4J_dbms_memory_heap_initial__size: "1G"
  NEO4J_dbms_memory_heap_max__size: "2G"
  NEO4J_dbms_memory_pagecache_size: "1G"
  NEO4J_dbms_connector_bolt_listen__address: "0.0.0.0:7687"
  NEO4J_dbms_connector_http_listen__address: "0.0.0.0:7474"
  NEO4J_apoc_export_file_enabled: "true"
  NEO4J_apoc_import_file_enabled: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: neo4j-data-pvc
  namespace: fortress-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-neo4j
  namespace: fortress-system
  labels:
    app: fortress-neo4j
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortress-neo4j
  template:
    metadata:
      labels:
        app: fortress-neo4j
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: neo4j
        image: neo4j:5.15-community
        ports:
        - containerPort: 7474
          name: http
          protocol: TCP
        - containerPort: 7687
          name: bolt
          protocol: TCP
        env:
        - name: NEO4J_AUTH
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_AUTH
        - name: NEO4J_dbms_default_database
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_default__database
        - name: NEO4J_dbms_security_procedures_unrestricted
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_security_procedures_unrestricted
        - name: NEO4J_dbms_security_procedures_allowlist
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_security_procedures_allowlist
        - name: NEO4J_dbms_memory_heap_initial_size
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_memory_heap_initial__size
        - name: NEO4J_dbms_memory_heap_max_size
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_memory_heap_max__size
        - name: NEO4J_dbms_memory_pagecache_size
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_memory_pagecache_size
        - name: NEO4J_dbms_connector_bolt_listen_address
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_connector_bolt_listen__address
        - name: NEO4J_dbms_connector_http_listen_address
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_dbms_connector_http_listen__address
        - name: NEO4J_apoc_export_file_enabled
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_apoc_export_file_enabled
        - name: NEO4J_apoc_import_file_enabled
          valueFrom:
            configMapKeyRef:
              name: neo4j-config
              key: NEO4J_apoc_import_file_enabled
        volumeMounts:
        - name: neo4j-data
          mountPath: /data
        - name: neo4j-logs
          mountPath: /logs
        resources:
          requests:
            memory: "2Gi"
            cpu: "500m"
          limits:
            memory: "4Gi"
            cpu: "2"
        livenessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 7474
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
      - name: neo4j-data
        persistentVolumeClaim:
          claimName: neo4j-data-pvc
      - name: neo4j-logs
        emptyDir: {}
      securityContext:
        fsGroup: 7474
        runAsUser: 7474
        runAsGroup: 7474
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-neo4j
  namespace: fortress-system
  labels:
    app: fortress-neo4j
spec:
  ports:
  - port: 7474
    targetPort: 7474
    protocol: TCP
    name: http
  - port: 7687
    targetPort: 7687
    protocol: TCP
    name: bolt
  selector:
    app: fortress-neo4j
  type: ClusterIP
