apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
    component: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        component: notifications
    spec:
      containers:
      - name: notification-service
        image: python:3.11-slim
        command: ["/bin/sh"]
        args: ["-c", "echo 'Notification Service - MCP Security Platform' && echo 'Ready to send security alerts and notifications' && tail -f /dev/null"]
        ports:
        - containerPort: 8085
        env:
        - name: SERVICE_NAME
          value: "notification-service"
        - name: DATABASE_URL
          value: "postgresql://mcp_user:SecureUserPassword123!@postgresql:5432/mcp_security"
        - name: REDIS_URL
          value: "redis://redis-master:6379/0"
        - name: LOG_LEVEL
          value: "info"
        - name: SMTP_HOST
          value: "localhost"
        - name: SMTP_PORT
          value: "587"
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Notification Service is alive'"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Notification Service is ready'"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification-service
    component: notifications
spec:
  selector:
    app: notification-service
  ports:
  - name: http
    port: 8085
    targetPort: 8085
    protocol: TCP
  type: ClusterIP
