apiVersion: v1
kind: Service
metadata:
  name: fortress-frontend
  labels:
    app: fortress-frontend
    component: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: fortress-frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fortress-ingress
  labels:
    app: fortress-frontend
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - fortress.company.com
    secretName: fortress-tls-secret
  rules:
  - host: fortress.company.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fortress-frontend
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: fortress-backend
            port:
              number: 8088
