apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-interface
  labels:
    app: web-interface
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-interface
  template:
    metadata:
      labels:
        app: web-interface
        component: frontend
    spec:
      containers:
      - name: web-interface
        image: localhost/fortress-web-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: SERVICE_NAME
          value: "web-interface"
        - name: API_GATEWAY_URL
          value: "http://gateway-service:8081"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8080"
        - name: REACT_APP_API_URL
          value: "http://10.63.89.182:30080/api"
        - name: REACT_APP_WS_URL
          value: "ws://10.63.89.182:30080/ws"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web-interface
  labels:
    app: web-interface
    component: frontend
spec:
  selector:
    app: web-interface
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
