apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fortress-platform-prod
  namespace: argocd
  labels:
    app.kubernetes.io/name: fortress-platform
    app.kubernetes.io/part-of: fortress-security
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ggkunka/fortress-gitops.git
    targetRevision: HEAD
    path: environments/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: fortress-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
