apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: ingress
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: mcp-security

resources:
- ingress.yaml

labels:
- pairs:
    app.kubernetes.io/name: ingress
    app.kubernetes.io/part-of: mcp-security-platform
    app.kubernetes.io/component: networking
    app.kubernetes.io/managed-by: argocd
