apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: mcp-security-monitoring
  labels:
    app.kubernetes.io/name: alertmanager-config
    app.kubernetes.io/component: monitoring
data:
  alertmanager.yml: |
    global:
      smtp_smarthost: 'smtp.company.com:587'
      smtp_from: 'alerts@security.company.com'
      smtp_auth_username: 'alerts@security.company.com'
      smtp_auth_password_file: '/etc/secrets/smtp-password'
    
    route:
      group_by: ['alertname', 'service']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        group_wait: 5s
        repeat_interval: 5m
      - match:
          component: scanner
        receiver: 'security-team'
      - match:
          component: vulnerability-analyzer
        receiver: 'security-team'
    
    receivers:
    - name: 'default'
      email_configs:
      - to: 'devops@company.com'
        subject: '[MCP Security] {{ .GroupLabels.alertname }}'
        body: |
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Severity: {{ .Labels.severity }}
          Service: {{ .Labels.service }}
          {{ end }}
    
    - name: 'critical-alerts'
      email_configs:
      - to: 'critical-alerts@company.com'
        subject: '[CRITICAL] MCP Security Platform Alert'
        body: |
          CRITICAL ALERT DETECTED
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          Time: {{ .StartsAt }}
          {{ end }}
      slack_configs:
      - api_url_file: '/etc/secrets/slack-webhook'
        channel: '#critical-alerts'
        title: 'Critical MCP Security Alert'
        text: |
          {{ range .Alerts }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          *Service:* {{ .Labels.service }}
          *Severity:* {{ .Labels.severity }}
          {{ end }}
    
    - name: 'security-team'
      email_configs:
      - to: 'security-team@company.com'
        subject: '[Security] MCP Platform Security Alert'
        body: |
          Security-related alert from MCP Platform:
          
          {{ range .Alerts }}
          Alert: {{ .Annotations.summary }}
          Description: {{ .Annotations.description }}
          Component: {{ .Labels.component }}
          Time: {{ .StartsAt }}
          {{ end }}
      slack_configs:
      - api_url_file: '/etc/secrets/security-slack-webhook'
        channel: '#security-alerts'
        title: 'MCP Security Platform Alert'
        text: |
          {{ range .Alerts }}
          *Component:* {{ .Labels.component }}
          *Alert:* {{ .Annotations.summary }}
          *Description:* {{ .Annotations.description }}
          {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-secrets
  namespace: mcp-security-monitoring
  labels:
    app.kubernetes.io/name: alertmanager-secrets
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  smtp-password: "your-smtp-password-here"
  slack-webhook: "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
  security-slack-webhook: "https://hooks.slack.com/services/YOUR/SECURITY/WEBHOOK"