apiVersion: v1
kind: Service
metadata:
  name: fortress-backend
  labels:
    app: fortress-backend
    component: backend
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8088"
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: fortress-backend
