apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: istio-infrastructure
  annotations:
    config.kubernetes.io/local-config: "true"

# Base Istio configuration from existing istio/ directory
resources:
# Use the existing Istio configuration
- ../../../istio/base/namespace.yaml
- ../../../istio/gateway/gateway.yaml
- ../../../istio/virtual-services/virtual-service.yaml
- ../../../istio/destination-rules/destination-rules.yaml
- ../../../istio/traffic-management/service-entry.yaml
- ../../../istio/traffic-management/envoy-filter.yaml
- ../../../istio/security/peer-authentication.yaml
- ../../../istio/security/request-authentication.yaml
- ../../../istio/security/authorization-policy.yaml
- ../../../istio/observability/telemetry.yaml

# Common labels for all Istio resources
commonLabels:
  app.kubernetes.io/name: istio-service-mesh
  app.kubernetes.io/part-of: mcp-security-platform
  app.kubernetes.io/managed-by: argocd
  istio.io/rev: default

# Environment-specific patches
patchesStrategicMerge:
- production-patches.yaml

# Configuration for production environment
configMapGenerator:
- name: istio-config
  literals:
  - ENVIRONMENT=production
  - ENABLE_MTLS=true
  - ENABLE_TRACING=true
  - ENABLE_METRICS=true
  - LOG_LEVEL=info
  - RATE_LIMIT_ENABLED=true
  - WAF_ENABLED=true