apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-oauth-service
  namespace: fortress-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress-oauth-service
  template:
    metadata:
      labels:
        app: fortress-oauth-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: oauth-service
        image: python:3.11-slim
        ports:
        - containerPort: 8090
        env:
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: oauth-code
          mountPath: /app
        command: ["/bin/bash"]
        args:
        - -c
        - |
          cd /app
          pip install fastapi uvicorn python-jose[cryptography] passlib[bcrypt] python-multipart
          python main.py
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: oauth-code
        configMap:
          name: fortress-oauth-code
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-oauth-service
  namespace: fortress-system
spec:
  selector:
    app: fortress-oauth-service
  ports:
  - port: 8090
    targetPort: 8090
  type: ClusterIP
