apiVersion: v2
name: analysis-service
description: MCP Security Platform Analysis Service - Performs threat analysis and MITRE ATT&CK mapping
type: application
version: 1.0.0
appVersion: "1.0.0"
kubeVersion: ">=1.21.0-0"

keywords:
  - mcp
  - security
  - analysis
  - mitre-attack
  - threat-analysis
  - microservice

home: https://github.com/mcp-security/platform
sources:
  - https://github.com/mcp-security/platform

maintainers:
  - name: MCP Security Platform Team
    email: platform@mcp-security.com

annotations:
  category: Security
  licenses: Apache-2.0