apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-trust-security
  labels:
    app: zero-trust-security
    component: security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zero-trust-security
  template:
    metadata:
      labels:
        app: zero-trust-security
        component: security
    spec:
      containers:
      - name: zero-trust-security
        image: mcp-security/zero-trust-security:latest
        ports:
        - containerPort: 8091
        resources:
          requests:
            memory: '256Mi'
            cpu: '100m'
          limits:
            memory: '512Mi'
            cpu: '300m'
        livenessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8091
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: zero-trust-security
  labels:
    app: zero-trust-security
spec:
  selector:
    app: zero-trust-security
  ports:
  - name: http
    port: 8091
    targetPort: 8091
  type: ClusterIP
