apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        component: authentication
    spec:
      containers:
      - name: auth-service
        image: python:3.11-slim
        command: ["/bin/sh"]
        args: ["-c", "echo 'Auth Service - MCP Security Platform' && echo 'Container ready for development' && tail -f /dev/null"]
        ports:
        - containerPort: 8080
        env:
        - name: SERVICE_NAME
          value: "auth-service"
        - name: DATABASE_URL
          value: "postgresql://mcp_user:SecureUserPassword123!@postgresql:5432/mcp_security"
        - name: REDIS_URL
          value: "redis://redis-master:6379/0"
        - name: LOG_LEVEL
          value: "info"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Service is alive'"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Service is ready'"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    app: auth-service
    component: authentication
spec:
  selector:
    app: auth-service
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
