# Codespaces POC Optimized Values
# Minimal resource configuration for 2-core/8GB Codespace environment

# Disable resource-intensive components for POC
monitoring:
  enabled: false  # Saves ~1GB RAM

prometheus:
  enabled: false

grafana:
  enabled: false

# Minimal service resources (64Mi RAM, 50m CPU per service)
services:
  ingestion:
    image:
      repository: "ghcr.io/ggkunka/mcp-correlation-engine"
      tag: "latest"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    
  enrichment:
    image:
      repository: "ghcr.io/ggkunka/mcp-risk-assessment"
      tag: "latest"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    
  gateway:
    image:
      repository: "ghcr.io/ggkunka/mcp-websocket-server"
      tag: "latest"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    service:
      port: 8000

  auth:
    image:
      repository: "ghcr.io/ggkunka/mcp-graphql-server"
      tag: "latest"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

  analysis:
    image:
      repository: "ghcr.io/ggkunka/mcp-response-orchestrator"
      tag: "latest"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

  notification:
    image:
      repository: "ghcr.io/ggkunka/mcp-reporting-service"
      tag: "latest"
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"

# Simplified database configuration
postgresql:
  enabled: true
  auth:
    postgresPassword: "mcp_password"
    username: "mcp_user"
    password: "mcp_password"
    database: "mcp_security"
  primary:
    persistence:
      enabled: false  # Faster startup without persistence
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
  metrics:
    enabled: false  # Disable metrics to avoid ServiceMonitor CRD requirement
    serviceMonitor:
      enabled: false

redis:
  enabled: true
  auth:
    enabled: true
    password: "redis_password"
  master:
    persistence:
      enabled: false  # Faster startup without persistence
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
  metrics:
    enabled: false  # Disable metrics to avoid ServiceMonitor CRD requirement
    serviceMonitor:
      enabled: false

# Disable complex services for POC
mongodb:
  enabled: false

influxdb:
  enabled: false

clickhouse:
  enabled: false

neo4j:
  enabled: false

minio:
  enabled: false

spark:
  enabled: false

# Simplified ingress for local development
ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /
          pathType: Prefix
          service:
            name: mcp-platform-gateway
            port: 8000
  tls: []

# Resource optimization settings
replicaCount: 1

# Disable advanced features for POC
plugins:
  enabled: false

eventStore:
  enabled: false

correlationEngine:
  enabled: false

riskAssessment:
  enabled: false

responseOrchestrator:
  enabled: false

# Total estimated resources: ~500Mi RAM, ~300m CPU