apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: observability
  annotations:
    config.kubernetes.io/local-config: "true"

namespace: mcp-security

resources:
- prometheus-stack.yaml
- grafana.yaml

labels:
- pairs:
    app.kubernetes.io/name: observability
    app.kubernetes.io/part-of: mcp-security-platform
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/managed-by: argocd
