{{- if and (eq (include "mcp-platform.isAKS" .) "true") .Values.kubernetesFlavorConfig.aks.appGateway.enabled -}}
{{- $fullName := include "mcp-platform.fullname" . -}}
{{- $svcPort := .Values.services.gateway.service.port -}}
{{- $ingressApiVersion := include "mcp-platform.ingress.apiVersion" . -}}
apiVersion: {{ $ingressApiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}-appgw
  labels:
    {{- include "mcp-platform.labels" . | nindent 4 }}
  annotations:
    {{- include "mcp-platform.annotations" . | nindent 4 }}
    # Application Gateway specific annotations
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    appgw.ingress.kubernetes.io/connection-draining: "true"
    appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
    appgw.ingress.kubernetes.io/cookie-based-affinity: "false"
    appgw.ingress.kubernetes.io/request-timeout: "30"
    {{- if .Values.kubernetesFlavorConfig.aks.appGateway.sslRedirect }}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    # Health check configuration
    appgw.ingress.kubernetes.io/health-probe-path: "/health"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399"
    appgw.ingress.kubernetes.io/health-probe-interval: "30"
    appgw.ingress.kubernetes.io/health-probe-timeout: "5"
    appgw.ingress.kubernetes.io/health-probe-unhealthy-threshold: "3"
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: Prefix
            backend:
              {{- if semverCompare ">=1.19.0" $.Capabilities.KubeVersion.Version }}
              service:
                name: {{ .service.name | default (printf "%s-gateway" $fullName) }}
                port:
                  number: {{ .service.port | default $svcPort }}
              {{- else }}
              serviceName: {{ .service.name | default (printf "%s-gateway" $fullName) }}
              servicePort: {{ .service.port | default $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}