{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-platform.serviceAccountName" . }}
  labels:
    {{- include "mcp-platform.labels" . | nindent 4 }}
  annotations:
    {{- include "mcp-platform.annotations" . | nindent 4 }}
    {{- include "mcp-platform.serviceAccountAnnotations" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}