apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
  labels:
    app: gateway-service
    component: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
        component: api-gateway
    spec:
      containers:
      - name: gateway-service
        image: mcp-security/gateway-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SERVICE_NAME
          value: "gateway-service"
        - name: DATABASE_URL
          value: "postgresql://mcp_user:SecureUserPassword123!@postgresql:5432/mcp_security"
        - name: REDIS_URL
          value: "redis://redis-master:6379/0"
        - name: LOG_LEVEL
          value: "info"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8080"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Gateway is alive'"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "echo 'Gateway is ready'"
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
    component: api-gateway
spec:
  selector:
    app: gateway-service
  ports:
  - name: http
    port: 8081
    targetPort: 8081
    protocol: TCP
  type: ClusterIP
