apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-cloud-integration
  namespace: fortress-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fortress-cloud-integration
  template:
    metadata:
      labels:
        app: fortress-cloud-integration
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: cloud-integration
        image: python:3.11-slim
        ports:
        - containerPort: 8093
        env:
        - name: AWS_REGION
          value: "us-east-1"
        - name: AZURE_TENANT_ID
          value: "placeholder-tenant"
        - name: GCP_PROJECT_ID
          value: "fortress-security"
        - name: PYTHONPATH
          value: "/app"
        volumeMounts:
        - name: cloud-code
          mountPath: /app
        command: ["/bin/bash"]
        args:
        - -c
        - |
          cd /app
          pip install fastapi uvicorn boto3 azure-identity azure-mgmt-security google-cloud-securitycenter
          python main.py
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8093
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8093
          initialDelaySeconds: 30
          periodSeconds: 5
      volumes:
      - name: cloud-code
        configMap:
          name: fortress-cloud-code
---
apiVersion: v1
kind: Service
metadata:
  name: fortress-cloud-integration
  namespace: fortress-system
spec:
  selector:
    app: fortress-cloud-integration
  ports:
  - port: 8093
    targetPort: 8093
  type: ClusterIP
