apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-registry
  namespace: mcp-security
data:
  clusters.yaml: |
    clusters:
      - name: "fortress"
        type: "k3s"
        endpoint: "https://10.63.89.182:6443"
        region: "on-premise"
        status: "active"
        description: "Main production cluster"
        kubeconfig: "/etc/kubeconfig/fortress-config"
        
      # Add your clusters here:
      - name: "production-aws"
        type: "eks"
        endpoint: "https://your-eks-cluster.region.eks.amazonaws.com"
        region: "us-west-2"
        status: "pending"
        description: "AWS EKS production cluster"
        kubeconfig: "/etc/kubeconfig/aws-prod-config"
        
      - name: "staging-azure"
        type: "aks"
        endpoint: "https://your-aks-cluster.region.azmk8s.io"
        region: "eastus"
        status: "pending"
        description: "Azure AKS staging cluster"
        kubeconfig: "/etc/kubeconfig/azure-staging-config"
        
      - name: "dev-gcp"
        type: "gke"
        endpoint: "https://your-gke-cluster.region.container.googleapis.com"
        region: "us-central1"
        status: "pending"
        description: "Google GKE development cluster"
        kubeconfig: "/etc/kubeconfig/gcp-dev-config"

---
apiVersion: v1
kind: Secret
metadata:
  name: cluster-credentials
  namespace: mcp-security
type: Opaque
data:
  # Base64 encoded kubeconfig files for each cluster
  fortress-config: |
    # Your fortress kubeconfig (already configured)
  aws-prod-config: |
    # Base64 encoded AWS EKS kubeconfig
  azure-staging-config: |
    # Base64 encoded Azure AKS kubeconfig  
  gcp-dev-config: |
    # Base64 encoded GCP GKE kubeconfig
