apiVersion: apps/v1
kind: Deployment
metadata:
  name: fortress-agent
  namespace: fortress-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fortress-agent
  template:
    metadata:
      labels:
        app: fortress-agent
    spec:
      serviceAccountName: fortress-agent
      containers:
      - name: agent
        image: fortress-agent:latest
        env:
        - name: FORTRESS_ENDPOINT
          value: "http://10.63.89.182:30080/api"
        - name: CLUSTER_NAME
          value: "REPLACE_WITH_CLUSTER_NAME"
        - name: CLUSTER_TYPE
          value: "REPLACE_WITH_CLUSTER_TYPE"
        - name: AGENT_TOKEN
          valueFrom:
            secretKeyRef:
              name: fortress-agent-token
              key: token
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fortress-agent
  namespace: fortress-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fortress-agent
rules:
- apiGroups: [""]
  resources: ["pods", "services", "nodes", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fortress-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fortress-agent
subjects:
- kind: ServiceAccount
  name: fortress-agent
  namespace: fortress-system

---
apiVersion: v1
kind: Secret
metadata:
  name: fortress-agent-token
  namespace: fortress-system
type: Opaque
data:
  token: Zm9ydHJlc3MtYWdlbnQtdG9rZW4tMTIzNDU2Nzg5MA== # fortress-agent-token-1234567890
