apiVersion: apps/v1
kind: Deployment
metadata:
  name: siem-integration
  labels:
    app: siem-integration
    component: external-integration
spec:
  replicas: 2
  selector:
    matchLabels:
      app: siem-integration
  template:
    metadata:
      labels:
        app: siem-integration
        component: external-integration
    spec:
      containers:
      - name: siem-integration
        image: mcp-security/siem-integration:latest
        ports:
        - containerPort: 8090
        resources:
          requests:
            memory: '128Mi'
            cpu: '50m'
          limits:
            memory: '256Mi'
            cpu: '200m'
        livenessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8090
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: siem-integration
  labels:
    app: siem-integration
spec:
  selector:
    app: siem-integration
  ports:
  - name: http
    port: 8090
    targetPort: 8090
  type: ClusterIP
