apiVersion: apps/v1
kind: Deployment
metadata:
  name: websocket-gateway
  labels:
    app: websocket-gateway
    component: realtime-communication
spec:
  replicas: 2
  selector:
    matchLabels:
      app: websocket-gateway
  template:
    metadata:
      labels:
        app: websocket-gateway
        component: realtime-communication
    spec:
      containers:
      - name: websocket-gateway
        image: mcp-security/websocket-gateway:latest
        ports:
        - containerPort: 8088
        env:
        - name: SERVICE_NAME
          value: "websocket-gateway"
        - name: LOG_LEVEL
          value: "info"
        - name: REDIS_URL
          value: "redis://redis-master:6379/0"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8088
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: websocket-gateway
  labels:
    app: websocket-gateway
    component: realtime-communication
spec:
  selector:
    app: websocket-gateway
  ports:
  - name: http
    port: 8088
    targetPort: 8088
    protocol: TCP
  type: ClusterIP
